modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="nieuwepoiemel"
version="1.0.0"
displayName="nieuwepoiemel"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="thijs, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.nieuwepoiemel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



